version: '3'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    user : root
    ports:
      - '1433:1433'
    volumes:
      - $PWD/mssql/data:/var/opt/mssql/data
      - $PWD/mssql/log:/var/opt/mssql/log
      - $PWD/mssql/secrets:/var/opt/mssql/secrets
    environment:
      ACCEPT_EULA : Y
      MSSQL_SA_PASSWORD: Passw0rd
    networks:
      - net

networks:
  net:


